name: Download Python Artifacts

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download Python ${{ matrix.python-version }} artifact
        run: |
          curl -O "https://www.python.org/ftp/python/${{ matrix.python-version }}/Python-${{ matrix.python-version }}.tar.xz"
          tar -xf "Python-${{ matrix.python-version }}.tar.xz" --strip-components=1 "Python-${{ matrix.python-version }}/Lib/test/*.txt"

      - name: Archive txt files
        run: |
          zip python_${{ matrix.python-version }}_txt_files.zip Python-${{ matrix.python-version }}/Lib/test/*.txt

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
