name: Download Python Artifacts

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download Python ${{ matrix.python-version }} artifact
        run: |
          curl -LO "https://www.python.org/ftp/python/${{ matrix.python-version }}/Python-${{ matrix.python-version }}.tar.xz"
          mkdir extracted_files
          tar -xf "Python-${{ matrix.python-version }}.tar.xz" -C extracted_files

      - name: Create txt files
        run: |
          mkdir txt_files
          find extracted_files -name "*.txt" -exec cp {} txt_files/ \;

      - name: Archive txt files
        run: |
          cd txt_files
          zip -r python_txt_files.zip ./

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
